// WBS Master Initial Data - Extracted from Google Sheet (23 Stages, Works, Tasks)
export const PMS_MASTER_STAGES_KEY = "pms_master_stages_data";
export const PMS_MASTER_WORKS_KEY = "pms_master_works_data";
export const PMS_MASTER_TASKS_KEY = "pms_master_tasks_data";

export const INITIAL_STAGES = [
  {
    "_id": "stage_s1",
    "stage_code": "S1",
    "stage_name": "STAGE 1",
    "description": "STAGE 1",
    "order": 1
  },
  {
    "_id": "stage_s2",
    "stage_code": "S2",
    "stage_name": "STAGE 2",
    "description": "STAGE 2",
    "order": 2
  },
  {
    "_id": "stage_s3",
    "stage_code": "S3",
    "stage_name": "STAGE 3",
    "description": "STAGE 3",
    "order": 3
  },
  {
    "_id": "stage_s4",
    "stage_code": "S4",
    "stage_name": "STAGE 4 = FOUNDATION WORK - 1",
    "description": "STAGE 4 = FOUNDATION WORK - 1",
    "order": 4
  },
  {
    "_id": "stage_s5",
    "stage_code": "S5",
    "stage_name": "STAGE 5 = FOUNDATION WORK - 2 [ FOOTING WORK ]",
    "description": "STAGE 5 = FOUNDATION WORK - 2 [ FOOTING WORK ]",
    "order": 5
  },
  {
    "_id": "stage_s6",
    "stage_code": "S6",
    "stage_name": "STAGE 6 = PLINTH / TIE BEAM CREATION",
    "description": "STAGE 6 = PLINTH / TIE BEAM CREATION",
    "order": 6
  },
  {
    "_id": "stage_s7",
    "stage_code": "S7",
    "stage_name": "STAGE 7 = COLUMN & DPC FORMATION",
    "description": "STAGE 7 = COLUMN & DPC FORMATION",
    "order": 7
  },
  {
    "_id": "stage_s8",
    "stage_code": "S8",
    "stage_name": "STAGE 8 = GROUND FLOOR",
    "description": "STAGE 8 = GROUND FLOOR",
    "order": 8
  },
  {
    "_id": "stage_s9",
    "stage_code": "S9",
    "stage_name": "STAGE 9 = SLAB CASTING",
    "description": "STAGE 9 = SLAB CASTING",
    "order": 9
  },
  {
    "_id": "stage_s10",
    "stage_code": "S10",
    "stage_name": "STAGE 10 = CONDUTING WORK (WALL & GROUND)  + NEXT FLOOR WORK (IF WANT WE CAN START NEXT FLOOR WITH CONDUITIND WORK )",
    "description": "STAGE 10 = CONDUTING WORK (WALL & GROUND)  + NEXT FLOOR WORK (IF WANT WE CAN START NEXT FLOOR WITH CONDUITIND WORK )",
    "order": 10
  },
  {
    "_id": "stage_s11",
    "stage_code": "S11",
    "stage_name": "STAGE 11 = PLASTERING = INTERNAL WALL",
    "description": "STAGE 11 = PLASTERING = INTERNAL WALL",
    "order": 11
  },
  {
    "_id": "stage_s12",
    "stage_code": "S12",
    "stage_name": "STAGE 12 (A)= PLASTERING = EXTERNAL WALL {FRONT}",
    "description": "STAGE 12 (A)= PLASTERING = EXTERNAL WALL {FRONT}",
    "order": 12
  },
  {
    "_id": "stage_s13",
    "stage_code": "S13",
    "stage_name": "STAGE 12 (B) = PLASTERING = EXTERNAL WALL {LEFT}",
    "description": "STAGE 12 (B) = PLASTERING = EXTERNAL WALL {LEFT}",
    "order": 13
  },
  {
    "_id": "stage_s14",
    "stage_code": "S14",
    "stage_name": "STAGE 12 (C)  = PLASTERING = EXTERNAL WALL {RIGHT}",
    "description": "STAGE 12 (C)  = PLASTERING = EXTERNAL WALL {RIGHT}",
    "order": 14
  },
  {
    "_id": "stage_s15",
    "stage_code": "S15",
    "stage_name": "STAGE 12 (D) = PLASTERING = EXTERNAL WALL {BACK}",
    "description": "STAGE 12 (D) = PLASTERING = EXTERNAL WALL {BACK}",
    "order": 15
  },
  {
    "_id": "stage_s16",
    "stage_code": "S16",
    "stage_name": "STAGE 13 = PUNNING & PUTTI WORK",
    "description": "STAGE 13 = PUNNING & PUTTI WORK",
    "order": 16
  },
  {
    "_id": "stage_s17",
    "stage_code": "S17",
    "stage_name": "STAGE 14 =  PRIMER & PAINT WORK",
    "description": "STAGE 14 =  PRIMER & PAINT WORK",
    "order": 17
  },
  {
    "_id": "stage_s18",
    "stage_code": "S18",
    "stage_name": "STAGE 15 =  ELECTRICAL WORK",
    "description": "STAGE 15 =  ELECTRICAL WORK",
    "order": 18
  },
  {
    "_id": "stage_s19",
    "stage_code": "S19",
    "stage_name": "STAGE 16 =  CEILING  WORK",
    "description": "STAGE 16 =  CEILING  WORK",
    "order": 19
  },
  {
    "_id": "stage_s20",
    "stage_code": "S20",
    "stage_name": "STAGE 17 =  FLOORING WORK",
    "description": "STAGE 17 =  FLOORING WORK",
    "order": 20
  },
  {
    "_id": "stage_s21",
    "stage_code": "S21",
    "stage_name": "STAGE 18 =  DOOR WORK",
    "description": "STAGE 18 =  DOOR WORK",
    "order": 21
  },
  {
    "_id": "stage_s22",
    "stage_code": "S22",
    "stage_name": "STAGE 19 = WINDOW WORK",
    "description": "STAGE 19 = WINDOW WORK",
    "order": 22
  },
  {
    "_id": "stage_s23",
    "stage_code": "S23",
    "stage_name": "STAGE 20 = SANITORY FITTING  WORK",
    "description": "STAGE 20 = SANITORY FITTING  WORK",
    "order": 23
  }
];

export const INITIAL_WORKS = [
  {
    "_id": "work_s1_w1",
    "stage_id": "stage_s1",
    "stage_code": "S1",
    "work_code": "S1-W1",
    "work_name": "SITE PREPRATION",
    "contractor_type": "Main Contractor",
    "order": 1
  },
  {
    "_id": "work_s2_w1",
    "stage_id": "stage_s2",
    "stage_code": "S2",
    "work_code": "S2-W1",
    "work_name": "LAYOUT WORK",
    "contractor_type": "Masonry Contractor",
    "order": 2
  },
  {
    "_id": "work_s3_w1",
    "stage_id": "stage_s3",
    "stage_code": "S3",
    "work_code": "S3-W1",
    "work_name": "EXCAVATION WORK",
    "contractor_type": "RCC Contractor",
    "order": 3
  },
  {
    "_id": "work_s3_w2",
    "stage_id": "stage_s3",
    "stage_code": "S3",
    "work_code": "S3-W2",
    "work_name": "BHUMI POOJAN",
    "contractor_type": "",
    "order": 4
  },
  {
    "_id": "work_s4_w1",
    "stage_id": "stage_s4",
    "stage_code": "S4",
    "work_code": "S4-W1",
    "work_name": "BASE PREPRATION",
    "contractor_type": "Civil Contractor",
    "order": 5
  },
  {
    "_id": "work_s4_w2",
    "stage_id": "stage_s4",
    "stage_code": "S4",
    "work_code": "S4-W2",
    "work_name": "PCC WORK",
    "contractor_type": "Marble Contractor",
    "order": 6
  },
  {
    "_id": "work_s5_w1",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "work_code": "S5-W1",
    "work_name": "REINFORCEMENT / BAR BINDING WORK",
    "contractor_type": "",
    "order": 7
  },
  {
    "_id": "work_s5_w2",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "work_code": "S5-W2",
    "work_name": "FOOTING BASE FORMATION",
    "contractor_type": "Fabrication Contractor",
    "order": 8
  },
  {
    "_id": "work_s5_w3",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "work_code": "S5-W3",
    "work_name": "FOUNDATION (FOOTING ) COLUMN WORK",
    "contractor_type": "Main Contractor",
    "order": 9
  },
  {
    "_id": "work_s5_w4",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "work_code": "S5-W4",
    "work_name": "FOUNDATION = PCC WORK [ FOR RETAINING BRICK WALL HOLDING ]",
    "contractor_type": "",
    "order": 10
  },
  {
    "_id": "work_s5_w5",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "work_code": "S5-W5",
    "work_name": "BRICK WORK [OUTER WALL , TILL PLINTH BEAM ]",
    "contractor_type": "",
    "order": 11
  },
  {
    "_id": "work_s5_w6",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "work_code": "S5-W6",
    "work_name": "BACKFILING - I [ PARTIAL BACKFILING ]",
    "contractor_type": "",
    "order": 12
  },
  {
    "_id": "work_s6_w1",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "work_code": "S6-W1",
    "work_name": "PCC WORK [Which Will Hold Plinth Beam ] [On Soil / On Brick ]",
    "contractor_type": "",
    "order": 13
  },
  {
    "_id": "work_s6_w2",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "work_code": "S6-W2",
    "work_name": "PLINTH / TIE BEAM",
    "contractor_type": "",
    "order": 14
  },
  {
    "_id": "work_s6_w3",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "work_code": "S6-W3",
    "work_name": "BACKFILING - II [ PARTIAL BACKFILING ]",
    "contractor_type": "",
    "order": 15
  },
  {
    "_id": "work_s7_w1",
    "stage_id": "stage_s7",
    "stage_code": "S7",
    "work_code": "S7-W1",
    "work_name": "COLUMN FORMATION [ ABOVE PLINTH BEAM ]",
    "contractor_type": "",
    "order": 16
  },
  {
    "_id": "work_s7_w2",
    "stage_id": "stage_s7",
    "stage_code": "S7",
    "work_code": "S7-W2",
    "work_name": "DPC [DAMP PROOF CASTING ] WORK",
    "contractor_type": "",
    "order": 17
  },
  {
    "_id": "work_s8_w1",
    "stage_id": "stage_s8",
    "stage_code": "S8",
    "work_code": "S8-W1",
    "work_name": "BRICK WORK { TILL LINTEL, WOODEN FRAME }",
    "contractor_type": "",
    "order": 18
  },
  {
    "_id": "work_s8_w2",
    "stage_id": "stage_s8",
    "stage_code": "S8",
    "work_code": "S8-W2",
    "work_name": "WOODEN FRAME WORK { According to Material = follow procedure }",
    "contractor_type": "",
    "order": 19
  },
  {
    "_id": "work_s8_w3",
    "stage_id": "stage_s8",
    "stage_code": "S8",
    "work_code": "S8-W3",
    "work_name": "LINTEL WORK { BEAM FORMATION = Above Doors , Windows , Ventilation etc. }",
    "contractor_type": "",
    "order": 20
  },
  {
    "_id": "work_s8_w4",
    "stage_id": "stage_s8",
    "stage_code": "S8",
    "work_code": "S8-W4",
    "work_name": "DO REMAING BRICK WORK OF GROUND FLOOR",
    "contractor_type": "",
    "order": 21
  },
  {
    "_id": "work_s9_w1",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "work_code": "S9-W1",
    "work_name": "WATER LABELING",
    "contractor_type": "",
    "order": 22
  },
  {
    "_id": "work_s9_w2",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "work_code": "S9-W2",
    "work_name": "SHUTTERING WORK = BEAM",
    "contractor_type": "",
    "order": 23
  },
  {
    "_id": "work_s9_w3",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "work_code": "S9-W3",
    "work_name": "SHUTTERING WORK = SLAB",
    "contractor_type": "",
    "order": 24
  },
  {
    "_id": "work_s9_w4",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "work_code": "S9-W4",
    "work_name": "CHECK COMPLETE STRUCTURE LABELING",
    "contractor_type": "",
    "order": 25
  },
  {
    "_id": "work_s9_w5",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "work_code": "S9-W5",
    "work_name": "BAR BINDING WORK",
    "contractor_type": "",
    "order": 26
  },
  {
    "_id": "work_s9_w6",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "work_code": "S9-W6",
    "work_name": "CUBE PLACEMENT WORK = BETWEEN BAR & SHUTTERING",
    "contractor_type": "",
    "order": 27
  },
  {
    "_id": "work_s9_w7",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "work_code": "S9-W7",
    "work_name": "ELECTRICAL CONDUITING WORK",
    "contractor_type": "",
    "order": 28
  },
  {
    "_id": "work_s9_w8",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "work_code": "S9-W8",
    "work_name": "PLUMBING SLEEVE WORK",
    "contractor_type": "",
    "order": 29
  },
  {
    "_id": "work_s9_w9",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "work_code": "S9-W9",
    "work_name": "PRE SLAB CASTING WORK",
    "contractor_type": "",
    "order": 30
  },
  {
    "_id": "work_s9_w10",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "work_code": "S9-W10",
    "work_name": "POOJA = Before Slab Casting",
    "contractor_type": "",
    "order": 31
  },
  {
    "_id": "work_s9_w11",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "work_code": "S9-W11",
    "work_name": "RCC WORK",
    "contractor_type": "",
    "order": 32
  },
  {
    "_id": "work_s10_w1",
    "stage_id": "stage_s10",
    "stage_code": "S10",
    "work_code": "S10-W1",
    "work_name": "ELECTRICAL CONDUITING WORK",
    "contractor_type": "",
    "order": 33
  },
  {
    "_id": "work_s10_w2",
    "stage_id": "stage_s10",
    "stage_code": "S10",
    "work_code": "S10-W2",
    "work_name": "PLUMBING CONDUITING WORK",
    "contractor_type": "",
    "order": 34
  },
  {
    "_id": "work_s10_w3",
    "stage_id": "stage_s10",
    "stage_code": "S10",
    "work_code": "S10-W3",
    "work_name": "A/C CONDUITING WORK (IF NEEDED)",
    "contractor_type": "",
    "order": 35
  },
  {
    "_id": "work_s10_w4",
    "stage_id": "stage_s10",
    "stage_code": "S10",
    "work_code": "S10-W4",
    "work_name": "FIBER OPTIC / SPEAKER / INTERNET / CAMERA CONDUITING WORK (IF NEEDED)",
    "contractor_type": "",
    "order": 36
  },
  {
    "_id": "work_s10_w5",
    "stage_id": "stage_s10",
    "stage_code": "S10",
    "work_code": "S10-W5",
    "work_name": "SOLAR CONDUITING WORK (IF NEEDED)",
    "contractor_type": "",
    "order": 37
  },
  {
    "_id": "work_s11_w1",
    "stage_id": "stage_s11",
    "stage_code": "S11",
    "work_code": "S11-W1",
    "work_name": "CURING = WALL & BRICK",
    "contractor_type": "",
    "order": 38
  },
  {
    "_id": "work_s11_w2",
    "stage_id": "stage_s11",
    "stage_code": "S11",
    "work_code": "S11-W2",
    "work_name": "FIBRE MESH WORK",
    "contractor_type": "",
    "order": 39
  },
  {
    "_id": "work_s11_w3",
    "stage_id": "stage_s11",
    "stage_code": "S11",
    "work_code": "S11-W3",
    "work_name": "MORTAR PREPARATION & PLASTERING",
    "contractor_type": "",
    "order": 40
  },
  {
    "_id": "work_s12_w1",
    "stage_id": "stage_s12",
    "stage_code": "S12",
    "work_code": "S12-W1",
    "work_name": "CURING = WALL & BRICK",
    "contractor_type": "",
    "order": 41
  },
  {
    "_id": "work_s12_w2",
    "stage_id": "stage_s12",
    "stage_code": "S12",
    "work_code": "S12-W2",
    "work_name": "FIBRE MESH WORK",
    "contractor_type": "",
    "order": 42
  },
  {
    "_id": "work_s12_w3",
    "stage_id": "stage_s12",
    "stage_code": "S12",
    "work_code": "S12-W3",
    "work_name": "MORTAR PREPARATION & PLASTERING",
    "contractor_type": "",
    "order": 43
  },
  {
    "_id": "work_s13_w1",
    "stage_id": "stage_s13",
    "stage_code": "S13",
    "work_code": "S13-W1",
    "work_name": "CURING = WALL & BRICK",
    "contractor_type": "",
    "order": 44
  },
  {
    "_id": "work_s13_w1",
    "stage_id": "stage_s13",
    "stage_code": "S13",
    "work_code": "S13-W1",
    "work_name": "FIBRE MESH WORK",
    "contractor_type": "",
    "order": 45
  },
  {
    "_id": "work_s13_w1",
    "stage_id": "stage_s13",
    "stage_code": "S13",
    "work_code": "S13-W1",
    "work_name": "MORTAR PREPARATION & PLASTERING",
    "contractor_type": "",
    "order": 46
  },
  {
    "_id": "work_s14_w1",
    "stage_id": "stage_s14",
    "stage_code": "S14",
    "work_code": "S14-W1",
    "work_name": "CURING = WALL & BRICK",
    "contractor_type": "",
    "order": 47
  },
  {
    "_id": "work_s14_w2",
    "stage_id": "stage_s14",
    "stage_code": "S14",
    "work_code": "S14-W2",
    "work_name": "FIBRE MESH WORK",
    "contractor_type": "",
    "order": 48
  },
  {
    "_id": "work_s14_w3",
    "stage_id": "stage_s14",
    "stage_code": "S14",
    "work_code": "S14-W3",
    "work_name": "MORTAR PREPARATION & PLASTERING",
    "contractor_type": "",
    "order": 49
  },
  {
    "_id": "work_s15_w1",
    "stage_id": "stage_s15",
    "stage_code": "S15",
    "work_code": "S15-W1",
    "work_name": "CURING = WALL & BRICK",
    "contractor_type": "",
    "order": 50
  },
  {
    "_id": "work_s15_w2",
    "stage_id": "stage_s15",
    "stage_code": "S15",
    "work_code": "S15-W2",
    "work_name": "FIBRE MESH WORK",
    "contractor_type": "",
    "order": 51
  },
  {
    "_id": "work_s15_w3",
    "stage_id": "stage_s15",
    "stage_code": "S15",
    "work_code": "S15-W3",
    "work_name": "MORTAR PREPARATION & PLASTERING",
    "contractor_type": "",
    "order": 52
  },
  {
    "_id": "work_s16_w1",
    "stage_id": "stage_s16",
    "stage_code": "S16",
    "work_code": "S16-W1",
    "work_name": "PUNNING",
    "contractor_type": "",
    "order": 53
  },
  {
    "_id": "work_s16_w2",
    "stage_id": "stage_s16",
    "stage_code": "S16",
    "work_code": "S16-W2",
    "work_name": "PUTTI WORK",
    "contractor_type": "",
    "order": 54
  },
  {
    "_id": "work_s17_w1",
    "stage_id": "stage_s17",
    "stage_code": "S17",
    "work_code": "S17-W1",
    "work_name": "RUBBING WORK",
    "contractor_type": "",
    "order": 55
  },
  {
    "_id": "work_s17_w2",
    "stage_id": "stage_s17",
    "stage_code": "S17",
    "work_code": "S17-W2",
    "work_name": "PRIMER",
    "contractor_type": "",
    "order": 56
  },
  {
    "_id": "work_s17_w3",
    "stage_id": "stage_s17",
    "stage_code": "S17",
    "work_code": "S17-W3",
    "work_name": "PAINT",
    "contractor_type": "",
    "order": 57
  },
  {
    "_id": "work_s18_w1",
    "stage_id": "stage_s18",
    "stage_code": "S18",
    "work_code": "S18-W1",
    "work_name": "WIRING WORK",
    "contractor_type": "",
    "order": 58
  },
  {
    "_id": "work_s18_w2",
    "stage_id": "stage_s18",
    "stage_code": "S18",
    "work_code": "S18-W2",
    "work_name": "SWITCH - SOCKET - FRAME - MCB WORK",
    "contractor_type": "",
    "order": 59
  },
  {
    "_id": "work_s18_w3",
    "stage_id": "stage_s18",
    "stage_code": "S18",
    "work_code": "S18-W3",
    "work_name": "EQUIPMENT",
    "contractor_type": "",
    "order": 60
  },
  {
    "_id": "work_s19_w1",
    "stage_id": "stage_s19",
    "stage_code": "S19",
    "work_code": "S19-W1",
    "work_name": "CEILING WORK",
    "contractor_type": "",
    "order": 61
  },
  {
    "_id": "work_s20_w1",
    "stage_id": "stage_s20",
    "stage_code": "S20",
    "work_code": "S20-W1",
    "work_name": "LOCATION 1",
    "contractor_type": "",
    "order": 62
  },
  {
    "_id": "work_s20_w2",
    "stage_id": "stage_s20",
    "stage_code": "S20",
    "work_code": "S20-W2",
    "work_name": "LOCATION 2",
    "contractor_type": "",
    "order": 63
  },
  {
    "_id": "work_s20_w3",
    "stage_id": "stage_s20",
    "stage_code": "S20",
    "work_code": "S20-W3",
    "work_name": "LOCATION 3",
    "contractor_type": "",
    "order": 64
  },
  {
    "_id": "work_s21_w1",
    "stage_id": "stage_s21",
    "stage_code": "S21",
    "work_code": "S21-W1",
    "work_name": "LOCATION 1",
    "contractor_type": "",
    "order": 65
  },
  {
    "_id": "work_s21_w2",
    "stage_id": "stage_s21",
    "stage_code": "S21",
    "work_code": "S21-W2",
    "work_name": "LOCATION 2",
    "contractor_type": "",
    "order": 66
  },
  {
    "_id": "work_s21_w3",
    "stage_id": "stage_s21",
    "stage_code": "S21",
    "work_code": "S21-W3",
    "work_name": "LOCATION 3",
    "contractor_type": "",
    "order": 67
  },
  {
    "_id": "work_s22_w1",
    "stage_id": "stage_s22",
    "stage_code": "S22",
    "work_code": "S22-W1",
    "work_name": "LOCATION 1",
    "contractor_type": "",
    "order": 68
  },
  {
    "_id": "work_s22_w2",
    "stage_id": "stage_s22",
    "stage_code": "S22",
    "work_code": "S22-W2",
    "work_name": "LOCATION 2",
    "contractor_type": "",
    "order": 69
  },
  {
    "_id": "work_s22_w3",
    "stage_id": "stage_s22",
    "stage_code": "S22",
    "work_code": "S22-W3",
    "work_name": "LOCATION 3",
    "contractor_type": "",
    "order": 70
  },
  {
    "_id": "work_s23_w1",
    "stage_id": "stage_s23",
    "stage_code": "S23",
    "work_code": "S23-W1",
    "work_name": "ALL TABS",
    "contractor_type": "",
    "order": 71
  },
  {
    "_id": "work_s23_w2",
    "stage_id": "stage_s23",
    "stage_code": "S23",
    "work_code": "S23-W2",
    "work_name": "WASHBASIN",
    "contractor_type": "",
    "order": 72
  },
  {
    "_id": "work_s23_w3",
    "stage_id": "stage_s23",
    "stage_code": "S23",
    "work_code": "S23-W3",
    "work_name": "CAMOD",
    "contractor_type": "",
    "order": 73
  },
  {
    "_id": "work_s23_w4",
    "stage_id": "stage_s23",
    "stage_code": "S23",
    "work_code": "S23-W4",
    "work_name": "DRAINAGE FITTING",
    "contractor_type": "",
    "order": 74
  },
  {
    "_id": "work_s23_w5",
    "stage_id": "stage_s23",
    "stage_code": "S23",
    "work_code": "S23-W5",
    "work_name": "MIRROR",
    "contractor_type": "",
    "order": 75
  },
  {
    "_id": "work_s23_w6",
    "stage_id": "stage_s23",
    "stage_code": "S23",
    "work_code": "S23-W6",
    "work_name": "OTHER FITTINGS ( NEEDFUL )",
    "contractor_type": "",
    "order": 76
  }
];

export const INITIAL_TASKS = [
  {
    "_id": "task_s1_w1_t1_0",
    "work_id": "work_s1_w1",
    "work_code": "S1-W1",
    "stage_id": "stage_s1",
    "stage_code": "S1",
    "task_code": "S1-W1-T1",
    "task_name": "CLEANING [ BY JCB / LABOUR ]",
    "work_done_by": "",
    "contractor_type": "Civil Contractor",
    "tools": "",
    "materials": "",
    "order": 1
  },
  {
    "_id": "task_s1_w1_t2_1",
    "work_id": "work_s1_w1",
    "work_code": "S1-W1",
    "stage_id": "stage_s1",
    "stage_code": "S1",
    "task_code": "S1-W1-T2",
    "task_name": "SITE LABELING [ BY LABLER VEHICLE / LABOUR / JCB ]",
    "work_done_by": "",
    "contractor_type": "Excavation Contractor",
    "tools": "",
    "materials": "",
    "order": 2
  },
  {
    "_id": "task_s1_w1_t3_2",
    "work_id": "work_s1_w1",
    "work_code": "S1-W1",
    "stage_id": "stage_s1",
    "stage_code": "S1",
    "task_code": "S1-W1-T3",
    "task_name": "CAMERA INSTALLATION",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "LABLER MACHINE",
    "materials": "Roofing Sheet, CPVC Pipe, Flush Door, Fly Ash Bricks",
    "order": 3
  },
  {
    "_id": "task_s1_w1_t4_3",
    "work_id": "work_s1_w1",
    "work_code": "S1-W1",
    "stage_id": "stage_s1",
    "stage_code": "S1",
    "task_code": "S1-W1-T4",
    "task_name": "SITE HORDING",
    "work_done_by": "",
    "contractor_type": "RCC Contractor",
    "tools": "",
    "materials": "",
    "order": 4
  },
  {
    "_id": "task_s1_w1_t5_4",
    "work_id": "work_s1_w1",
    "work_code": "S1-W1",
    "stage_id": "stage_s1",
    "stage_code": "S1",
    "task_code": "S1-W1-T5",
    "task_name": "BARRICATING",
    "work_done_by": "",
    "contractor_type": "Shuttering Contractor",
    "tools": "",
    "materials": "",
    "order": 5
  },
  {
    "_id": "task_s1_w1_t6_5",
    "work_id": "work_s1_w1",
    "work_code": "S1-W1",
    "stage_id": "stage_s1",
    "stage_code": "S1",
    "task_code": "S1-W1-T6",
    "task_name": "MATERIAL STORAGE AREA PREPRATION",
    "work_done_by": "",
    "contractor_type": "RCC Contractor",
    "tools": "",
    "materials": "",
    "order": 6
  },
  {
    "_id": "task_s1_w1_t7_6",
    "work_id": "work_s1_w1",
    "work_code": "S1-W1",
    "stage_id": "stage_s1",
    "stage_code": "S1",
    "task_code": "S1-W1-T7",
    "task_name": "TOOLS STORAGE AREA PREPRATION",
    "work_done_by": "",
    "contractor_type": "RCC Contractor",
    "tools": "",
    "materials": "",
    "order": 7
  },
  {
    "_id": "task_s1_w1_t8_7",
    "work_id": "work_s1_w1",
    "work_code": "S1-W1",
    "stage_id": "stage_s1",
    "stage_code": "S1",
    "task_code": "S1-W1-T8",
    "task_name": "LABOUR STAY AREA PREPRATION",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 8
  },
  {
    "_id": "task_s1_w1_t9_8",
    "work_id": "work_s1_w1",
    "work_code": "S1-W1",
    "stage_id": "stage_s1",
    "stage_code": "S1",
    "task_code": "S1-W1-T9",
    "task_name": "SITE ENGINEER SITTING AREA PREPRATIONS / SITE OFFICE PREPRATION",
    "work_done_by": "",
    "contractor_type": "RCC Contractor",
    "tools": "",
    "materials": "",
    "order": 9
  },
  {
    "_id": "task_s1_w1_t10_9",
    "work_id": "work_s1_w1",
    "work_code": "S1-W1",
    "stage_id": "stage_s1",
    "stage_code": "S1",
    "task_code": "S1-W1-T10",
    "task_name": "ELECTRICITY SUPPLY MANAGEMENT",
    "work_done_by": "",
    "contractor_type": "Civil Contractor",
    "tools": "",
    "materials": "",
    "order": 10
  },
  {
    "_id": "task_s1_w1_t11_10",
    "work_id": "work_s1_w1",
    "work_code": "S1-W1",
    "stage_id": "stage_s1",
    "stage_code": "S1",
    "task_code": "S1-W1-T11",
    "task_name": "WATER SUPPLY MANAGEMENT",
    "work_done_by": "",
    "contractor_type": "Civil Contractor",
    "tools": "",
    "materials": "",
    "order": 11
  },
  {
    "_id": "task_s2_w1_t1_11",
    "work_id": "work_s2_w1",
    "work_code": "S2-W1",
    "stage_id": "stage_s2",
    "stage_code": "S2",
    "task_code": "S2-W1-T1",
    "task_name": "SITE MARKING",
    "work_done_by": "",
    "contractor_type": "RCC Contractor",
    "tools": "",
    "materials": "",
    "order": 12
  },
  {
    "_id": "task_s2_w1_t2_12",
    "work_id": "work_s2_w1",
    "work_code": "S2-W1",
    "stage_id": "stage_s2",
    "stage_code": "S2",
    "task_code": "S2-W1-T2",
    "task_name": "FOOTING",
    "work_done_by": "",
    "contractor_type": "Shuttering Contractor",
    "tools": "",
    "materials": "",
    "order": 13
  },
  {
    "_id": "task_s3_w1_t1_13",
    "work_id": "work_s3_w1",
    "work_code": "S3-W1",
    "stage_id": "stage_s3",
    "stage_code": "S3",
    "task_code": "S3-W1-T1",
    "task_name": "FOOTING MARKING = EXCAVATION [ BY JCB / LABOUR ]",
    "work_done_by": "",
    "contractor_type": "RCC Contractor",
    "tools": "",
    "materials": "",
    "order": 14
  },
  {
    "_id": "task_s3_w1_t2_14",
    "work_id": "work_s3_w1",
    "work_code": "S3-W1",
    "stage_id": "stage_s3",
    "stage_code": "S3",
    "task_code": "S3-W1-T2",
    "task_name": "FOOTING EXCAVATION = DRESSING [ BY LABOUR ]",
    "work_done_by": "",
    "contractor_type": "Masonry Contractor",
    "tools": "",
    "materials": "",
    "order": 15
  },
  {
    "_id": "task_s3_w1_t3_15",
    "work_id": "work_s3_w1",
    "work_code": "S3-W1",
    "stage_id": "stage_s3",
    "stage_code": "S3",
    "task_code": "S3-W1-T3",
    "task_name": "FOOTING EXCAVATION = CURING  [ BY LABOUR ]",
    "work_done_by": "",
    "contractor_type": "Plaster Contractor",
    "tools": "",
    "materials": "",
    "order": 16
  },
  {
    "_id": "task_s3_w2_t1_16",
    "work_id": "work_s3_w2",
    "work_code": "S3-W2",
    "stage_id": "stage_s3",
    "stage_code": "S3",
    "task_code": "S3-W2-T1",
    "task_name": "POOJA = IF CLIENT WANT",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 17
  },
  {
    "_id": "task_s4_w1_t1_17",
    "work_id": "work_s4_w1",
    "work_code": "S4-W1",
    "stage_id": "stage_s4",
    "stage_code": "S4",
    "task_code": "S4-W1-T1",
    "task_name": "BASE PREPRATION",
    "work_done_by": "LABOUR",
    "contractor_type": "Tile Contractor",
    "tools": "",
    "materials": "",
    "order": 18
  },
  {
    "_id": "task_s4_w2_t1_18",
    "work_id": "work_s4_w2",
    "work_code": "S4-W2",
    "stage_id": "stage_s4",
    "stage_code": "S4",
    "task_code": "S4-W2-T1",
    "task_name": "Blasting Work",
    "work_done_by": "LABOUR, DURMUT",
    "contractor_type": "Electrical Contractor",
    "tools": "",
    "materials": "",
    "order": 19
  },
  {
    "_id": "task_s4_w2_t2_19",
    "work_id": "work_s4_w2",
    "work_code": "S4-W2",
    "stage_id": "stage_s4",
    "stage_code": "S4",
    "task_code": "S4-W2-T2",
    "task_name": "HAMMERING",
    "work_done_by": "LABOUR",
    "contractor_type": "Electrical Contractor",
    "tools": "DURMUT",
    "materials": "",
    "order": 20
  },
  {
    "_id": "task_s4_w2_t3_20",
    "work_id": "work_s4_w2",
    "work_code": "S4-W2",
    "stage_id": "stage_s4",
    "stage_code": "S4",
    "task_code": "S4-W2-T3",
    "task_name": "M-10 OR M-15 /  MORTAR [CEMENT + MAURANG] / CONTREATE [ CEMENT + SAND + GSB GITTI ]",
    "work_done_by": "LABOUR",
    "contractor_type": "Plumbing Contractor",
    "tools": "MIXING MACHINE",
    "materials": "",
    "order": 21
  },
  {
    "_id": "task_s4_w2_t4_21",
    "work_id": "work_s4_w2",
    "work_code": "S4-W2",
    "stage_id": "stage_s4",
    "stage_code": "S4",
    "task_code": "S4-W2-T4",
    "task_name": "HAMMERING",
    "work_done_by": "LABOUR",
    "contractor_type": "Sanitary Contractor",
    "tools": "DURMUT",
    "materials": "",
    "order": 22
  },
  {
    "_id": "task_s4_w2_t5_22",
    "work_id": "work_s4_w2",
    "work_code": "S4-W2",
    "stage_id": "stage_s4",
    "stage_code": "S4",
    "task_code": "S4-W2-T5",
    "task_name": "CURING",
    "work_done_by": "LABOUR",
    "contractor_type": "Carpentry Contractor",
    "tools": "",
    "materials": "",
    "order": 23
  },
  {
    "_id": "task_s5_w1_t1_23",
    "work_id": "work_s5_w1",
    "work_code": "S5-W1",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W1-T1",
    "task_name": "BAR STRAITNING WORK",
    "work_done_by": "LABOUR - BAR BINDER [LOHAR]",
    "contractor_type": "Window Contractor",
    "tools": "BAR BINDER'S [LOHAR'S] TOOL",
    "materials": "",
    "order": 24
  },
  {
    "_id": "task_s5_w1_t2_24",
    "work_id": "work_s5_w1",
    "work_code": "S5-W1",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W1-T2",
    "task_name": "FOOTING = BAR FORMATON",
    "work_done_by": "LABOUR - BAR BINDER [LOHAR]",
    "contractor_type": "Interior Contractor",
    "tools": "BAR BINDER'S [LOHAR'S] TOOL",
    "materials": "",
    "order": 25
  },
  {
    "_id": "task_s5_w1_t3_25",
    "work_id": "work_s5_w1",
    "work_code": "S5-W1",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W1-T3",
    "task_name": "COLUMN = BAR FORMATION",
    "work_done_by": "LABOUR - BAR BINDER [LOHAR]",
    "contractor_type": "Painting Contractor",
    "tools": "BAR BINDER'S [LOHAR'S] TOOL",
    "materials": "",
    "order": 26
  },
  {
    "_id": "task_s5_w1_t4_26",
    "work_id": "work_s5_w1",
    "work_code": "S5-W1",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W1-T4",
    "task_name": "FOOTING & COLUMN =  FORMED BAR PLACEMENT",
    "work_done_by": "LABOUR - BAR BINDER [LOHAR]",
    "contractor_type": "Painting Contractor",
    "tools": "",
    "materials": "",
    "order": 27
  },
  {
    "_id": "task_s5_w1_t5_27",
    "work_id": "work_s5_w1",
    "work_code": "S5-W1",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W1-T5",
    "task_name": "CHRECK LABLE = BY LABLER",
    "work_done_by": "LABOUR",
    "contractor_type": "Painting Contractor",
    "tools": "SAHUL (LATTU)",
    "materials": "",
    "order": 28
  },
  {
    "_id": "task_s5_w2_t1_28",
    "work_id": "work_s5_w2",
    "work_code": "S5-W2",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W2-T1",
    "task_name": "SHUTTERING OF FOOTING WORK",
    "work_done_by": "CONTRACTOR = SHUTTERING",
    "contractor_type": "Interior Contractor",
    "tools": "",
    "materials": "",
    "order": 29
  },
  {
    "_id": "task_s5_w2_t2_29",
    "work_id": "work_s5_w2",
    "work_code": "S5-W2",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W2-T2",
    "task_name": "M 25 - M30 CONCRETE PREPARATION, POURING, WORK",
    "work_done_by": "LABOUR",
    "contractor_type": "Interior Contractor",
    "tools": "VIBRATOR",
    "materials": "",
    "order": 30
  },
  {
    "_id": "task_s5_w2_t3_30",
    "work_id": "work_s5_w2",
    "work_code": "S5-W2",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W2-T3",
    "task_name": "CURING",
    "work_done_by": "",
    "contractor_type": "Electrical Contractor",
    "tools": "",
    "materials": "",
    "order": 31
  },
  {
    "_id": "task_s5_w3_t1_31",
    "work_id": "work_s5_w3",
    "work_code": "S5-W3",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W3-T1",
    "task_name": "CHECK COLUMN LABEL",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 32
  },
  {
    "_id": "task_s5_w3_t2_32",
    "work_id": "work_s5_w3",
    "work_code": "S5-W3",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W3-T2",
    "task_name": "DO SHUTTERING WORK = FOR STARTER",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 33
  },
  {
    "_id": "task_s5_w3_t3_33",
    "work_id": "work_s5_w3",
    "work_code": "S5-W3",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W3-T3",
    "task_name": "M 25 - M30 CONCRETE PREPARATION, POURING, WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 34
  },
  {
    "_id": "task_s5_w3_t4_34",
    "work_id": "work_s5_w3",
    "work_code": "S5-W3",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W3-T4",
    "task_name": "CURING WORK - STARTER FORMED",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 35
  },
  {
    "_id": "task_s5_w3_t5_35",
    "work_id": "work_s5_w3",
    "work_code": "S5-W3",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W3-T5",
    "task_name": "DO SHUTTERING WORK = FOR FOOTING COLUMN",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 36
  },
  {
    "_id": "task_s5_w3_t6_36",
    "work_id": "work_s5_w3",
    "work_code": "S5-W3",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W3-T6",
    "task_name": "M 25 - M30 CONCRETE PREPARATION, POURING, WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 37
  },
  {
    "_id": "task_s5_w3_t7_37",
    "work_id": "work_s5_w3",
    "work_code": "S5-W3",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W3-T7",
    "task_name": "CURING WORK - COLUMN  FORMED",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 38
  },
  {
    "_id": "task_s5_w4_t1_38",
    "work_id": "work_s5_w4",
    "work_code": "S5-W4",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W4-T1",
    "task_name": "Blasting Work",
    "work_done_by": "LABOUR, DURMUT",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 39
  },
  {
    "_id": "task_s5_w4_t2_39",
    "work_id": "work_s5_w4",
    "work_code": "S5-W4",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W4-T2",
    "task_name": "HAMMERING",
    "work_done_by": "LABOUR",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 40
  },
  {
    "_id": "task_s5_w4_t3_40",
    "work_id": "work_s5_w4",
    "work_code": "S5-W4",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W4-T3",
    "task_name": "M-10 OR M-15 /  MORTAR [CEMENT + MAURANG] / CONTREATE [ CEMENT + SAND + GSB GITTI ]",
    "work_done_by": "LABOUR",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 41
  },
  {
    "_id": "task_s5_w4_t4_41",
    "work_id": "work_s5_w4",
    "work_code": "S5-W4",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W4-T4",
    "task_name": "HAMMERING",
    "work_done_by": "LABOUR",
    "contractor_type": "Plumbing Contractor",
    "tools": "",
    "materials": "",
    "order": 42
  },
  {
    "_id": "task_s5_w4_t5_42",
    "work_id": "work_s5_w4",
    "work_code": "S5-W4",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W4-T5",
    "task_name": "CURING",
    "work_done_by": "LABOUR",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 43
  },
  {
    "_id": "task_s5_w5_t1_43",
    "work_id": "work_s5_w5",
    "work_code": "S5-W5",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W5-T1",
    "task_name": "Blasting Work",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 44
  },
  {
    "_id": "task_s5_w6_t1_44",
    "work_id": "work_s5_w6",
    "work_code": "S5-W6",
    "stage_id": "stage_s5",
    "stage_code": "S5",
    "task_code": "S5-W6-T1",
    "task_name": "FOR BUILDING TIE BEAM - TO SUPPORT [We Perform Partial Backfiling ]",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 45
  },
  {
    "_id": "task_s6_w1_t1_45",
    "work_id": "work_s6_w1",
    "work_code": "S6-W1",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "task_code": "S6-W1-T1",
    "task_name": "Blasting Work",
    "work_done_by": "LABOUR, DURMUT",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 46
  },
  {
    "_id": "task_s6_w1_t2_46",
    "work_id": "work_s6_w1",
    "work_code": "S6-W1",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "task_code": "S6-W1-T2",
    "task_name": "HAMMERING",
    "work_done_by": "LABOUR",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 47
  },
  {
    "_id": "task_s6_w1_t3_47",
    "work_id": "work_s6_w1",
    "work_code": "S6-W1",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "task_code": "S6-W1-T3",
    "task_name": "M-10 OR M-15 /  MORTAR [CEMENT + MAURANG] / CONTREATE [ CEMENT + SAND + GSB GITTI ]",
    "work_done_by": "LABOUR",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 48
  },
  {
    "_id": "task_s6_w1_t4_48",
    "work_id": "work_s6_w1",
    "work_code": "S6-W1",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "task_code": "S6-W1-T4",
    "task_name": "HAMMERING",
    "work_done_by": "LABOUR",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 49
  },
  {
    "_id": "task_s6_w1_t5_49",
    "work_id": "work_s6_w1",
    "work_code": "S6-W1",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "task_code": "S6-W1-T5",
    "task_name": "CURING",
    "work_done_by": "LABOUR",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 50
  },
  {
    "_id": "task_s6_w2_t1_50",
    "work_id": "work_s6_w2",
    "work_code": "S6-W2",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "task_code": "S6-W2-T1",
    "task_name": "CHECK SURFACE LABEL",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 51
  },
  {
    "_id": "task_s6_w2_t2_51",
    "work_id": "work_s6_w2",
    "work_code": "S6-W2",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "task_code": "S6-W2-T2",
    "task_name": "PREPAIRE & PLACE = BAR BINDING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 52
  },
  {
    "_id": "task_s6_w2_t3_52",
    "work_id": "work_s6_w2",
    "work_code": "S6-W2",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "task_code": "S6-W2-T3",
    "task_name": "CUBES PLACEMENT",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 53
  },
  {
    "_id": "task_s6_w2_t4_53",
    "work_id": "work_s6_w2",
    "work_code": "S6-W2",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "task_code": "S6-W2-T4",
    "task_name": "DO COMPLETE SHUTTERING WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 54
  },
  {
    "_id": "task_s6_w2_t5_54",
    "work_id": "work_s6_w2",
    "work_code": "S6-W2",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "task_code": "S6-W2-T5",
    "task_name": "CLEANING OF SHUTTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 55
  },
  {
    "_id": "task_s6_w2_t6_55",
    "work_id": "work_s6_w2",
    "work_code": "S6-W2",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "task_code": "S6-W2-T6",
    "task_name": "OILING OF SHUTTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 56
  },
  {
    "_id": "task_s6_w2_t7_56",
    "work_id": "work_s6_w2",
    "work_code": "S6-W2",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "task_code": "S6-W2-T7",
    "task_name": "M 25 - M30 CONCRETE PREPARATION, POURING, WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 57
  },
  {
    "_id": "task_s6_w2_t8_57",
    "work_id": "work_s6_w2",
    "work_code": "S6-W2",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "task_code": "S6-W2-T8",
    "task_name": "CURING WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 58
  },
  {
    "_id": "task_s6_w3_t1_58",
    "work_id": "work_s6_w3",
    "work_code": "S6-W3",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "task_code": "S6-W3-T1",
    "task_name": "DO BACKFILING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 59
  },
  {
    "_id": "task_s6_w3_t2_59",
    "work_id": "work_s6_w3",
    "work_code": "S6-W3",
    "stage_id": "stage_s6",
    "stage_code": "S6",
    "task_code": "S6-W3-T2",
    "task_name": "COMPACTION",
    "work_done_by": "LABOUR",
    "contractor_type": "",
    "tools": "DURMUT",
    "materials": "",
    "order": 60
  },
  {
    "_id": "task_s7_w1_t1_60",
    "work_id": "work_s7_w1",
    "work_code": "S7-W1",
    "stage_id": "stage_s7",
    "stage_code": "S7",
    "task_code": "S7-W1-T1",
    "task_name": "CHECK SURFACE LABEL",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 61
  },
  {
    "_id": "task_s7_w1_t2_61",
    "work_id": "work_s7_w1",
    "work_code": "S7-W1",
    "stage_id": "stage_s7",
    "stage_code": "S7",
    "task_code": "S7-W1-T2",
    "task_name": "FORM COLUMN STARTER",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 62
  },
  {
    "_id": "task_s7_w1_t3_62",
    "work_id": "work_s7_w1",
    "work_code": "S7-W1",
    "stage_id": "stage_s7",
    "stage_code": "S7",
    "task_code": "S7-W1-T3",
    "task_name": "PREPAIRE & PLACE = BAR BINDING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 63
  },
  {
    "_id": "task_s7_w1_t4_63",
    "work_id": "work_s7_w1",
    "work_code": "S7-W1",
    "stage_id": "stage_s7",
    "stage_code": "S7",
    "task_code": "S7-W1-T4",
    "task_name": "CUBES PLACEMENT",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 64
  },
  {
    "_id": "task_s7_w1_t5_64",
    "work_id": "work_s7_w1",
    "work_code": "S7-W1",
    "stage_id": "stage_s7",
    "stage_code": "S7",
    "task_code": "S7-W1-T5",
    "task_name": "DO COMPLETE SHUTTERING WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 65
  },
  {
    "_id": "task_s7_w1_t6_65",
    "work_id": "work_s7_w1",
    "work_code": "S7-W1",
    "stage_id": "stage_s7",
    "stage_code": "S7",
    "task_code": "S7-W1-T6",
    "task_name": "CLEANING OF SHUTTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 66
  },
  {
    "_id": "task_s7_w1_t7_66",
    "work_id": "work_s7_w1",
    "work_code": "S7-W1",
    "stage_id": "stage_s7",
    "stage_code": "S7",
    "task_code": "S7-W1-T7",
    "task_name": "OILING OF SHUTTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 67
  },
  {
    "_id": "task_s7_w1_t8_67",
    "work_id": "work_s7_w1",
    "work_code": "S7-W1",
    "stage_id": "stage_s7",
    "stage_code": "S7",
    "task_code": "S7-W1-T8",
    "task_name": "M 25 - M30 CONCRETE PREPARATION, POURING, WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 68
  },
  {
    "_id": "task_s7_w1_t9_68",
    "work_id": "work_s7_w1",
    "work_code": "S7-W1",
    "stage_id": "stage_s7",
    "stage_code": "S7",
    "task_code": "S7-W1-T9",
    "task_name": "CURING WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 69
  },
  {
    "_id": "task_s7_w1_t10_69",
    "work_id": "work_s7_w1",
    "work_code": "S7-W1",
    "stage_id": "stage_s7",
    "stage_code": "S7",
    "task_code": "S7-W1-T10",
    "task_name": "OPEN SHUTTERING IN 1-2 DAYS",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 70
  },
  {
    "_id": "task_s7_w2_t1_70",
    "work_id": "work_s7_w2",
    "work_code": "S7-W2",
    "stage_id": "stage_s7",
    "stage_code": "S7",
    "task_code": "S7-W2-T1",
    "task_name": "CLEAN & PREPAIRE SURFACE = FOR DPC WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 71
  },
  {
    "_id": "task_s7_w2_t2_71",
    "work_id": "work_s7_w2",
    "work_code": "S7-W2",
    "stage_id": "stage_s7",
    "stage_code": "S7",
    "task_code": "S7-W2-T2",
    "task_name": "M 20 =CONCRETE PREPRATION[ CEMENT + SAND + JEERA GITTI (10MM) ] (Without BAR )  & POURING(2.5mm - 3mm Layering)",
    "work_done_by": "LABOUR",
    "contractor_type": "",
    "tools": "MIXING MACHINE",
    "materials": "",
    "order": 72
  },
  {
    "_id": "task_s7_w2_t3_72",
    "work_id": "work_s7_w2",
    "work_code": "S7-W2",
    "stage_id": "stage_s7",
    "stage_code": "S7",
    "task_code": "S7-W2-T3",
    "task_name": "DPC CURING",
    "work_done_by": "LABOUR",
    "contractor_type": "",
    "tools": "WATER SYSTEM MANAGEMENT",
    "materials": "",
    "order": 73
  },
  {
    "_id": "task_s8_w1_t1_73",
    "work_id": "work_s8_w1",
    "work_code": "S8-W1",
    "stage_id": "stage_s8",
    "stage_code": "S8",
    "task_code": "S8-W1-T1",
    "task_name": "START BRICK CASTING WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 74
  },
  {
    "_id": "task_s8_w1_t2_74",
    "work_id": "work_s8_w1",
    "work_code": "S8-W1",
    "stage_id": "stage_s8",
    "stage_code": "S8",
    "task_code": "S8-W1-T2",
    "task_name": "SEALBAND = AT EVERY 5 FEET / MID OF WALL RCC [CONCREATE + BAR ( REWIRED IN COLUMN ) PUT SEALBAND OF 5 Inch - 6 Inch  During Wall Casting",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 75
  },
  {
    "_id": "task_s8_w1_t3_75",
    "work_id": "work_s8_w1",
    "work_code": "S8-W1",
    "stage_id": "stage_s8",
    "stage_code": "S8",
    "task_code": "S8-W1-T3",
    "task_name": "PERFORM BRICKWORK = PERFORM BRICK JOINTS",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 76
  },
  {
    "_id": "task_s8_w1_t4_76",
    "work_id": "work_s8_w1",
    "work_code": "S8-W1",
    "stage_id": "stage_s8",
    "stage_code": "S8",
    "task_code": "S8-W1-T4",
    "task_name": "PERFORM TAKKING ( BY HAMMER ) / REWIRING ( BR BAR ) BETWEEN EVERY JOINTS / TOUCH POINTS OF BRICK SURFACE & COLUMN SURFACE",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 77
  },
  {
    "_id": "task_s8_w2_t1_77",
    "work_id": "work_s8_w2",
    "work_code": "S8-W2",
    "stage_id": "stage_s8",
    "stage_code": "S8",
    "task_code": "S8-W2-T1",
    "task_name": "DOORS",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 78
  },
  {
    "_id": "task_s8_w2_t2_78",
    "work_id": "work_s8_w2",
    "work_code": "S8-W2",
    "stage_id": "stage_s8",
    "stage_code": "S8",
    "task_code": "S8-W2-T2",
    "task_name": "WINDOWS",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 79
  },
  {
    "_id": "task_s8_w2_t3_79",
    "work_id": "work_s8_w2",
    "work_code": "S8-W2",
    "stage_id": "stage_s8",
    "stage_code": "S8",
    "task_code": "S8-W2-T3",
    "task_name": "WASHROOM VENTILATION",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 80
  },
  {
    "_id": "task_s8_w3_t1_80",
    "work_id": "work_s8_w3",
    "work_code": "S8-W3",
    "stage_id": "stage_s8",
    "stage_code": "S8",
    "task_code": "S8-W3-T1",
    "task_name": "M20 / M25 :  RCC = { CEMENT : SAND : GRAVEL(10 mm) : BAR } : Prepration & Pouring",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 81
  },
  {
    "_id": "task_s8_w3_t2_81",
    "work_id": "work_s8_w3",
    "work_code": "S8-W3",
    "stage_id": "stage_s8",
    "stage_code": "S8",
    "task_code": "S8-W3-T2",
    "task_name": "Use Proper Shuttering Work",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 82
  },
  {
    "_id": "task_s8_w3_t3_82",
    "work_id": "work_s8_w3",
    "work_code": "S8-W3",
    "stage_id": "stage_s8",
    "stage_code": "S8",
    "task_code": "S8-W3-T3",
    "task_name": "Do Curing Work Properly",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 83
  },
  {
    "_id": "task_s8_w4_t1_83",
    "work_id": "work_s8_w4",
    "work_code": "S8-W4",
    "stage_id": "stage_s8",
    "stage_code": "S8",
    "task_code": "S8-W4-T1",
    "task_name": "COMPLETE BRICK WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 84
  },
  {
    "_id": "task_s9_w1_t1_84",
    "work_id": "work_s9_w1",
    "work_code": "S9-W1",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W1-T1",
    "task_name": "WATER LABELING = BY LABELING PIPE",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 85
  },
  {
    "_id": "task_s9_w2_t1_85",
    "work_id": "work_s9_w2",
    "work_code": "S9-W2",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W2-T1",
    "task_name": "METAL / PLYBOARD BEAM SHUTTERING FORMATION START",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 86
  },
  {
    "_id": "task_s9_w2_t2_86",
    "work_id": "work_s9_w2",
    "work_code": "S9-W2",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W2-T2",
    "task_name": "REMOVE DUST / OBSTACLE ETC. = FROM INNER SURFACE OF SHUTTERING (BY BLOWER ) ( MULTIPLE TIME )",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 87
  },
  {
    "_id": "task_s9_w2_t3_87",
    "work_id": "work_s9_w2",
    "work_code": "S9-W2",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W2-T3",
    "task_name": "CHECK LEAKAGE / OPENING AND FIX IT ( BY Dr. FIXIT TAPE)",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 88
  },
  {
    "_id": "task_s9_w2_t4_88",
    "work_id": "work_s9_w2",
    "work_code": "S9-W2",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W2-T4",
    "task_name": "METAL / PLYBOARD BEAM SHUTTERING FORMATION START",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 89
  },
  {
    "_id": "task_s9_w2_t5_89",
    "work_id": "work_s9_w2",
    "work_code": "S9-W2",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W2-T5",
    "task_name": "DO OILING WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 90
  },
  {
    "_id": "task_s9_w2_t6_90",
    "work_id": "work_s9_w2",
    "work_code": "S9-W2",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W2-T6",
    "task_name": "METAL / PLYBOARD BEAM SHUTTERING FORMATION COMPLETED",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 91
  },
  {
    "_id": "task_s9_w3_t1_91",
    "work_id": "work_s9_w3",
    "work_code": "S9-W3",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W3-T1",
    "task_name": "METAL / PLYBOARD SLAB SHUTTERING FORMATION START",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 92
  },
  {
    "_id": "task_s9_w3_t2_92",
    "work_id": "work_s9_w3",
    "work_code": "S9-W3",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W3-T2",
    "task_name": "REMOVE DUST / OBSTACLE ETC. = FROM INNER SURFACE OF SHUTTERING (BY BLOWER ) ( MULTIPLE TIME )",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 93
  },
  {
    "_id": "task_s9_w3_t3_93",
    "work_id": "work_s9_w3",
    "work_code": "S9-W3",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W3-T3",
    "task_name": "CHECK LEAKAGE / OPENING AND FIX IT ( BY Dr. FIXIT TAPE)",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 94
  },
  {
    "_id": "task_s9_w3_t4_94",
    "work_id": "work_s9_w3",
    "work_code": "S9-W3",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W3-T4",
    "task_name": "METAL / PLYBOARD BEAM SHUTTERING FORMATION START",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 95
  },
  {
    "_id": "task_s9_w3_t5_95",
    "work_id": "work_s9_w3",
    "work_code": "S9-W3",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W3-T5",
    "task_name": "DO OILING WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 96
  },
  {
    "_id": "task_s9_w3_t6_96",
    "work_id": "work_s9_w3",
    "work_code": "S9-W3",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W3-T6",
    "task_name": "METAL / PLYBOARD SLAB SHUTTERING FORMATION END",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 97
  },
  {
    "_id": "task_s9_w4_t1_97",
    "work_id": "work_s9_w4",
    "work_code": "S9-W4",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W4-T1",
    "task_name": "STRUCTURE LABELING CHECK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 98
  },
  {
    "_id": "task_s9_w5_t1_98",
    "work_id": "work_s9_w5",
    "work_code": "S9-W5",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W5-T1",
    "task_name": "BAR BINDING WORK = BEAM",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 99
  },
  {
    "_id": "task_s9_w5_t2_99",
    "work_id": "work_s9_w5",
    "work_code": "S9-W5",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W5-T2",
    "task_name": "BAR BINDING WORK = SLAB",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 100
  },
  {
    "_id": "task_s9_w6_t1_100",
    "work_id": "work_s9_w6",
    "work_code": "S9-W6",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W6-T1",
    "task_name": "25 mm^3 = concrete cubes (Readymade Purchased )",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 101
  },
  {
    "_id": "task_s9_w6_t2_101",
    "work_id": "work_s9_w6",
    "work_code": "S9-W6",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W6-T2",
    "task_name": "BAR BINDING WORK = SLAB",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 102
  },
  {
    "_id": "task_s9_w7_t1_102",
    "work_id": "work_s9_w7",
    "work_code": "S9-W7",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W7-T1",
    "task_name": "PERFORM ELECTRICAL CONDUITING WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 103
  },
  {
    "_id": "task_s9_w8_t1_103",
    "work_id": "work_s9_w8",
    "work_code": "S9-W8",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W8-T1",
    "task_name": "PERFORM PLUMBING SLEEVE WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 104
  },
  {
    "_id": "task_s9_w9_t1_104",
    "work_id": "work_s9_w9",
    "work_code": "S9-W9",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W9-T1",
    "task_name": "CHECK COMPLETE STRUCTURE'S LABELING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 105
  },
  {
    "_id": "task_s9_w9_t2_105",
    "work_id": "work_s9_w9",
    "work_code": "S9-W9",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W9-T2",
    "task_name": "CHECK BAR BINDING WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 106
  },
  {
    "_id": "task_s9_w9_t3_106",
    "work_id": "work_s9_w9",
    "work_code": "S9-W9",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W9-T3",
    "task_name": "CHECK ELECTRICAL CONDUITING WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 107
  },
  {
    "_id": "task_s9_w9_t4_107",
    "work_id": "work_s9_w9",
    "work_code": "S9-W9",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W9-T4",
    "task_name": "CHECK MATERIAL PREPARATION WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 108
  },
  {
    "_id": "task_s9_w9_t5_108",
    "work_id": "work_s9_w9",
    "work_code": "S9-W9",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W9-T5",
    "task_name": "TOLLS & MACHINE AVAILABILITY CHECK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 109
  },
  {
    "_id": "task_s9_w9_t6_109",
    "work_id": "work_s9_w9",
    "work_code": "S9-W9",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W9-T6",
    "task_name": "EXPERT MANPOWER PRESENCE CHECK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 110
  },
  {
    "_id": "task_s9_w10_t1_110",
    "work_id": "work_s9_w10",
    "work_code": "S9-W10",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W10-T1",
    "task_name": "CHECK COMPLETE STRUCTURE'S LABELING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 111
  },
  {
    "_id": "task_s9_w11_t1_111",
    "work_id": "work_s9_w11",
    "work_code": "S9-W11",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W11-T1",
    "task_name": "M-25 / M-30 CONCRETE = PREPRATION",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 112
  },
  {
    "_id": "task_s9_w11_t2_112",
    "work_id": "work_s9_w11",
    "work_code": "S9-W11",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W11-T2",
    "task_name": "PERFORM = SLUMP TEST / CUBE TEST",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 113
  },
  {
    "_id": "task_s9_w11_t3_113",
    "work_id": "work_s9_w11",
    "work_code": "S9-W11",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W11-T3",
    "task_name": "PERFORM MIXING & POURING OF CONCRETE",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 114
  },
  {
    "_id": "task_s9_w11_t4_114",
    "work_id": "work_s9_w11",
    "work_code": "S9-W11",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W11-T4",
    "task_name": "USE VIBRATOR = TO SET & DISTRIBUTE CONCRETE",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 115
  },
  {
    "_id": "task_s9_w11_t5_115",
    "work_id": "work_s9_w11",
    "work_code": "S9-W11",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W11-T5",
    "task_name": "RCC WORK COMPLETED",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 116
  },
  {
    "_id": "task_s9_w11_t6_116",
    "work_id": "work_s9_w11",
    "work_code": "S9-W11",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W11-T6",
    "task_name": "MAKE FRAME / KYARI  ON SLAB SURFACE = TO HOLD WATER",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 117
  },
  {
    "_id": "task_s9_w11_t7_117",
    "work_id": "work_s9_w11",
    "work_code": "S9-W11",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W11-T7",
    "task_name": "CURING BY WATER",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 118
  },
  {
    "_id": "task_s9_w11_t8_118",
    "work_id": "work_s9_w11",
    "work_code": "S9-W11",
    "stage_id": "stage_s9",
    "stage_code": "S9",
    "task_code": "S9-W11-T8",
    "task_name": "OPEN SHUTTERING BETWEEN (15-21 DAYS )",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 119
  },
  {
    "_id": "task_s9_w1_t1_119",
    "work_id": "work_s10_w1",
    "work_code": "S10-W1",
    "stage_id": "stage_s10",
    "stage_code": "S10",
    "task_code": "S9-W1-T1",
    "task_name": "MARKING (BY CHALK) ACCORDING TO DRAWING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 120
  },
  {
    "_id": "task_s9_w1_t2_120",
    "work_id": "work_s10_w1",
    "work_code": "S10-W1",
    "stage_id": "stage_s10",
    "stage_code": "S10",
    "task_code": "S9-W1-T2",
    "task_name": "CHEESELING(JHEERI) = BY \"WALL CHEESELING MACHINE\" [ NEVER USE GRINDER MACHINE & CHISEL-HAMMER(CHHENI-HATHAUDI) ]",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 121
  },
  {
    "_id": "task_s9_w1_t3_121",
    "work_id": "work_s10_w1",
    "work_code": "S10-W1",
    "stage_id": "stage_s10",
    "stage_code": "S10",
    "task_code": "S9-W1-T3",
    "task_name": "DESIGN ELECTRICAL SHAFT = FOR ELECTRICITY DISTRIBUTION FROM ONE FLOOR TO OTHER",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 122
  },
  {
    "_id": "task_s10_w2_t1_122",
    "work_id": "work_s10_w2",
    "work_code": "S10-W2",
    "stage_id": "stage_s10",
    "stage_code": "S10",
    "task_code": "S10-W2-T1",
    "task_name": "MARKING (BY CHALK) ACCORDING TO DRAWING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 123
  },
  {
    "_id": "task_s10_w2_t2_123",
    "work_id": "work_s10_w2",
    "work_code": "S10-W2",
    "stage_id": "stage_s10",
    "stage_code": "S10",
    "task_code": "S10-W2-T2",
    "task_name": "CHEESELING(JHEERI) = BY \"WALL CHEESELING MACHINE\" [ NEVER USE GRINDER MACHINE & CHISEL-HAMMER(CHHENI-HATHAUDI) ]",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 124
  },
  {
    "_id": "task_s10_w2_t3_124",
    "work_id": "work_s10_w2",
    "work_code": "S10-W2",
    "stage_id": "stage_s10",
    "stage_code": "S10",
    "task_code": "S10-W2-T3",
    "task_name": "CUTTING OF SLAB FOR WATER FLOW / DRAINAGE",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 125
  },
  {
    "_id": "task_s10_w3_t1_125",
    "work_id": "work_s10_w3",
    "work_code": "S10-W3",
    "stage_id": "stage_s10",
    "stage_code": "S10",
    "task_code": "S10-W3-T1",
    "task_name": "START & COMPLETE = A/C CONDUITING WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 126
  },
  {
    "_id": "task_s10_w4_t1_126",
    "work_id": "work_s10_w4",
    "work_code": "S10-W4",
    "stage_id": "stage_s10",
    "stage_code": "S10",
    "task_code": "S10-W4-T1",
    "task_name": "START & COMPLETE = FIBER OPTIC / SPEAKER / INTERNET CONDUITING WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 127
  },
  {
    "_id": "task_s10_w5_t1_127",
    "work_id": "work_s10_w5",
    "work_code": "S10-W5",
    "stage_id": "stage_s10",
    "stage_code": "S10",
    "task_code": "S10-W5-T1",
    "task_name": "START & COMPLETE = SOLAR CONDUITING WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 128
  },
  {
    "_id": "task_s11_w1_t1_128",
    "work_id": "work_s11_w1",
    "work_code": "S11-W1",
    "stage_id": "stage_s11",
    "stage_code": "S11",
    "task_code": "S11-W1-T1",
    "task_name": "FROM 1 DAY PRIOR OF PLASTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 129
  },
  {
    "_id": "task_s11_w1_t2_129",
    "work_id": "work_s11_w1",
    "work_code": "S11-W1",
    "stage_id": "stage_s11",
    "stage_code": "S11",
    "task_code": "S11-W1-T2",
    "task_name": "DO CURING = BEFORE 15 MINUTES OF PLASTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 130
  },
  {
    "_id": "task_s11_w2_t2_130",
    "work_id": "work_s11_w2",
    "work_code": "S11-W2",
    "stage_id": "stage_s11",
    "stage_code": "S11",
    "task_code": "S11-W2-T2",
    "task_name": "AT JOINT BETWEEN RCC & BRICK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 131
  },
  {
    "_id": "task_s11_w2_t3_131",
    "work_id": "work_s11_w2",
    "work_code": "S11-W2",
    "stage_id": "stage_s11",
    "stage_code": "S11",
    "task_code": "S11-W2-T3",
    "task_name": "ABOVE (ON) ALL CONDUTING OPENING BETWEEN BRICK - TO - BRICK JOINTS = BRICK CROSS / WRONG BRICK WORK NOT ALLOWED",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 132
  },
  {
    "_id": "task_s11_w3_t1_132",
    "work_id": "work_s11_w3",
    "work_code": "S11-W3",
    "stage_id": "stage_s11",
    "stage_code": "S11",
    "task_code": "S11-W3-T1",
    "task_name": "START & COMPLETE =MORTAR PREPARATION & PLASTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 133
  },
  {
    "_id": "task_s12_w1_t1_133",
    "work_id": "work_s12_w1",
    "work_code": "S12-W1",
    "stage_id": "stage_s12",
    "stage_code": "S12",
    "task_code": "S12-W1-T1",
    "task_name": "FROM 1 DAY PRIOR OF PLASTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 134
  },
  {
    "_id": "task_s12_w1_t2_134",
    "work_id": "work_s12_w1",
    "work_code": "S12-W1",
    "stage_id": "stage_s12",
    "stage_code": "S12",
    "task_code": "S12-W1-T2",
    "task_name": "DO CURING = BEFORE 15 MINUTES OF PLASTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 135
  },
  {
    "_id": "task_s12_w2_t1_135",
    "work_id": "work_s12_w2",
    "work_code": "S12-W2",
    "stage_id": "stage_s12",
    "stage_code": "S12",
    "task_code": "S12-W2-T1",
    "task_name": "AT JOINT BETWEEN RCC & BRICK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 136
  },
  {
    "_id": "task_s12_w2_t2_136",
    "work_id": "work_s12_w2",
    "work_code": "S12-W2",
    "stage_id": "stage_s12",
    "stage_code": "S12",
    "task_code": "S12-W2-T2",
    "task_name": "ABOVE (ON) ALL CONDUTING OPENING BETWEEN BRICK - TO - BRICK JOINTS = BRICK CROSS / WRONG BRICK WORK NOT ALLOWED",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 137
  },
  {
    "_id": "task_s12_w3_t1_137",
    "work_id": "work_s12_w3",
    "work_code": "S12-W3",
    "stage_id": "stage_s12",
    "stage_code": "S12",
    "task_code": "S12-W3-T1",
    "task_name": "START & COMPLETE =MORTAR PREPARATION & PLASTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 138
  },
  {
    "_id": "task_s13_w1_t1_138",
    "work_id": "work_s13_w1",
    "work_code": "S13-W1",
    "stage_id": "stage_s13",
    "stage_code": "S13",
    "task_code": "S13-W1-T1",
    "task_name": "FROM 1 DAY PRIOR OF PLASTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 139
  },
  {
    "_id": "task_s13_w1_t2_139",
    "work_id": "work_s13_w1",
    "work_code": "S13-W1",
    "stage_id": "stage_s13",
    "stage_code": "S13",
    "task_code": "S13-W1-T2",
    "task_name": "DO CURING = BEFORE 15 MINUTES OF PLASTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 140
  },
  {
    "_id": "task_s13_w2_t1_140",
    "work_id": "work_s13_w1",
    "work_code": "S13-W1",
    "stage_id": "stage_s13",
    "stage_code": "S13",
    "task_code": "S13-W2-T1",
    "task_name": "AT JOINT BETWEEN RCC & BRICK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 141
  },
  {
    "_id": "task_s13_w2_t2_141",
    "work_id": "work_s13_w1",
    "work_code": "S13-W1",
    "stage_id": "stage_s13",
    "stage_code": "S13",
    "task_code": "S13-W2-T2",
    "task_name": "ABOVE (ON) ALL CONDUTING OPENING BETWEEN BRICK - TO - BRICK JOINTS = BRICK CROSS / WRONG BRICK WORK NOT ALLOWED",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 142
  },
  {
    "_id": "task_s13_w3_t1_142",
    "work_id": "work_s13_w1",
    "work_code": "S13-W1",
    "stage_id": "stage_s13",
    "stage_code": "S13",
    "task_code": "S13-W3-T1",
    "task_name": "START & COMPLETE =MORTAR PREPARATION & PLASTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 143
  },
  {
    "_id": "task_s14_w1_t1_143",
    "work_id": "work_s14_w1",
    "work_code": "S14-W1",
    "stage_id": "stage_s14",
    "stage_code": "S14",
    "task_code": "S14-W1-T1",
    "task_name": "FROM 1 DAY PRIOR OF PLASTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 144
  },
  {
    "_id": "task_s14_w1_t2_144",
    "work_id": "work_s14_w1",
    "work_code": "S14-W1",
    "stage_id": "stage_s14",
    "stage_code": "S14",
    "task_code": "S14-W1-T2",
    "task_name": "DO CURING = BEFORE 15 MINUTES OF PLASTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 145
  },
  {
    "_id": "task_s14_w2_t1_145",
    "work_id": "work_s14_w2",
    "work_code": "S14-W2",
    "stage_id": "stage_s14",
    "stage_code": "S14",
    "task_code": "S14-W2-T1",
    "task_name": "AT JOINT BETWEEN RCC & BRICK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 146
  },
  {
    "_id": "task_s14_w2_t2_146",
    "work_id": "work_s14_w2",
    "work_code": "S14-W2",
    "stage_id": "stage_s14",
    "stage_code": "S14",
    "task_code": "S14-W2-T2",
    "task_name": "ABOVE (ON) ALL CONDUTING OPENING BETWEEN BRICK - TO - BRICK JOINTS = BRICK CROSS / WRONG BRICK WORK NOT ALLOWED",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 147
  },
  {
    "_id": "task_s14_w3_t1_147",
    "work_id": "work_s14_w3",
    "work_code": "S14-W3",
    "stage_id": "stage_s14",
    "stage_code": "S14",
    "task_code": "S14-W3-T1",
    "task_name": "START & COMPLETE =MORTAR PREPARATION & PLASTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 148
  },
  {
    "_id": "task_s15_w1_t1_148",
    "work_id": "work_s15_w1",
    "work_code": "S15-W1",
    "stage_id": "stage_s15",
    "stage_code": "S15",
    "task_code": "S15-W1-T1",
    "task_name": "FROM 1 DAY PRIOR OF PLASTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 149
  },
  {
    "_id": "task_s15_w1_t2_149",
    "work_id": "work_s15_w1",
    "work_code": "S15-W1",
    "stage_id": "stage_s15",
    "stage_code": "S15",
    "task_code": "S15-W1-T2",
    "task_name": "DO CURING = BEFORE 15 MINUTES OF PLASTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 150
  },
  {
    "_id": "task_s15_w2_t1_150",
    "work_id": "work_s15_w2",
    "work_code": "S15-W2",
    "stage_id": "stage_s15",
    "stage_code": "S15",
    "task_code": "S15-W2-T1",
    "task_name": "AT JOINT BETWEEN RCC & BRICK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 151
  },
  {
    "_id": "task_s15_w2_t2_151",
    "work_id": "work_s15_w2",
    "work_code": "S15-W2",
    "stage_id": "stage_s15",
    "stage_code": "S15",
    "task_code": "S15-W2-T2",
    "task_name": "ABOVE (ON) ALL CONDUTING OPENING BETWEEN BRICK - TO - BRICK JOINTS = BRICK CROSS / WRONG BRICK WORK NOT ALLOWED",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 152
  },
  {
    "_id": "task_s15_w3_t1_152",
    "work_id": "work_s15_w3",
    "work_code": "S15-W3",
    "stage_id": "stage_s15",
    "stage_code": "S15",
    "task_code": "S15-W3-T1",
    "task_name": "START & COMPLETE =MORTAR PREPARATION & PLASTERING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 153
  },
  {
    "_id": "task_s16_w1_t1_153",
    "work_id": "work_s16_w1",
    "work_code": "S16-W1",
    "stage_id": "stage_s16",
    "stage_code": "S16",
    "task_code": "S16-W1-T1",
    "task_name": "TUCKING WORK { NO NEED IF WALL IS CEMENTED OR  RUBB SURFACE }",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 154
  },
  {
    "_id": "task_s16_w1_t2_154",
    "work_id": "work_s16_w1",
    "work_code": "S16-W1",
    "stage_id": "stage_s16",
    "stage_code": "S16",
    "task_code": "S16-W1-T2",
    "task_name": "APPLY BOND ON SURFACE ( SAKARANI BRAND USUALY)",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 155
  },
  {
    "_id": "task_s16_w1_t3_155",
    "work_id": "work_s16_w1",
    "work_code": "S16-W1",
    "stage_id": "stage_s16",
    "stage_code": "S16",
    "task_code": "S16-W1-T3",
    "task_name": "PLUMMING & LABELING WORK ( BY POP )",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 156
  },
  {
    "_id": "task_s16_w2_t1_156",
    "work_id": "work_s16_w2",
    "work_code": "S16-W2",
    "stage_id": "stage_s16",
    "stage_code": "S16",
    "task_code": "S16-W2-T1",
    "task_name": "COAT 1 { INCLUIDE CEILING ALSO ( IF NEEDED ) }",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 157
  },
  {
    "_id": "task_s16_w2_t2_157",
    "work_id": "work_s16_w2",
    "work_code": "S16-W2",
    "stage_id": "stage_s16",
    "stage_code": "S16",
    "task_code": "S16-W2-T2",
    "task_name": "COAT 2 ( IF NEEDED )",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 158
  },
  {
    "_id": "task_s17_w1_t1_158",
    "work_id": "work_s17_w1",
    "work_code": "S17-W1",
    "stage_id": "stage_s17",
    "stage_code": "S17",
    "task_code": "S17-W1-T1",
    "task_name": "RUBBING { BY REGMALL / MACHINE }",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 159
  },
  {
    "_id": "task_s17_w2_t1_159",
    "work_id": "work_s17_w2",
    "work_code": "S17-W2",
    "stage_id": "stage_s17",
    "stage_code": "S17",
    "task_code": "S17-W2-T1",
    "task_name": "1 COAT",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 160
  },
  {
    "_id": "task_s17_w3_t1_160",
    "work_id": "work_s17_w3",
    "work_code": "S17-W3",
    "stage_id": "stage_s17",
    "stage_code": "S17",
    "task_code": "S17-W3-T1",
    "task_name": "COAT 1",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 161
  },
  {
    "_id": "task_s17_w3_t2_161",
    "work_id": "work_s17_w3",
    "work_code": "S17-W3",
    "stage_id": "stage_s17",
    "stage_code": "S17",
    "task_code": "S17-W3-T2",
    "task_name": "COAT 2 ( DO AFTER WHOLE WORK COMPLETION & BEFORE KEY HANDOVER TO CLIENT )",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 162
  },
  {
    "_id": "task_s18_w1_t1_162",
    "work_id": "work_s18_w1",
    "work_code": "S18-W1",
    "stage_id": "stage_s18",
    "stage_code": "S18",
    "task_code": "S18-W1-T1",
    "task_name": "ELECTRICAL WIRING",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 163
  },
  {
    "_id": "task_s18_w1_t2_163",
    "work_id": "work_s18_w1",
    "work_code": "S18-W1",
    "stage_id": "stage_s18",
    "stage_code": "S18",
    "task_code": "S18-W1-T2",
    "task_name": "CAMERA WIRING ( IF NEEDED )",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 164
  },
  {
    "_id": "task_s18_w1_t3_164",
    "work_id": "work_s18_w1",
    "work_code": "S18-W1",
    "stage_id": "stage_s18",
    "stage_code": "S18",
    "task_code": "S18-W1-T3",
    "task_name": "INTERNET  WIRING ( IF NEEDED )",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 165
  },
  {
    "_id": "task_s18_w1_t4_165",
    "work_id": "work_s18_w1",
    "work_code": "S18-W1",
    "stage_id": "stage_s18",
    "stage_code": "S18",
    "task_code": "S18-W1-T4",
    "task_name": "SPEAKER WIRING ( IF NEEDED )",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 166
  },
  {
    "_id": "task_s18_w1_t5_166",
    "work_id": "work_s18_w1",
    "work_code": "S18-W1",
    "stage_id": "stage_s18",
    "stage_code": "S18",
    "task_code": "S18-W1-T5",
    "task_name": "SOLAR WIRING ( IF NEEDED )",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 167
  },
  {
    "_id": "task_s18_w2_t1_167",
    "work_id": "work_s18_w2",
    "work_code": "S18-W2",
    "stage_id": "stage_s18",
    "stage_code": "S18",
    "task_code": "S18-W2-T1",
    "task_name": "ALL HOUSE EQUIPMENT",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 168
  },
  {
    "_id": "task_s18_w3_t1_168",
    "work_id": "work_s18_w3",
    "work_code": "S18-W3",
    "stage_id": "stage_s18",
    "stage_code": "S18",
    "task_code": "S18-W3-T1",
    "task_name": "LIGHT",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 169
  },
  {
    "_id": "task_s18_w3_t2_169",
    "work_id": "work_s18_w3",
    "work_code": "S18-W3",
    "stage_id": "stage_s18",
    "stage_code": "S18",
    "task_code": "S18-W3-T2",
    "task_name": "APPLIANCE",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 170
  },
  {
    "_id": "task_s18_w3_t3_170",
    "work_id": "work_s18_w3",
    "work_code": "S18-W3",
    "stage_id": "stage_s18",
    "stage_code": "S18",
    "task_code": "S18-W3-T3",
    "task_name": "CAMERA ( IF EXIST )",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 171
  },
  {
    "_id": "task_s18_w3_t4_171",
    "work_id": "work_s18_w3",
    "work_code": "S18-W3",
    "stage_id": "stage_s18",
    "stage_code": "S18",
    "task_code": "S18-W3-T4",
    "task_name": "SOLAR ( IF EXIST )",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 172
  },
  {
    "_id": "task_s18_w3_t5_172",
    "work_id": "work_s18_w3",
    "work_code": "S18-W3",
    "stage_id": "stage_s18",
    "stage_code": "S18",
    "task_code": "S18-W3-T5",
    "task_name": "SPEAKER ( IF EXIST )",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 173
  },
  {
    "_id": "task_s18_w3_t6_173",
    "work_id": "work_s18_w3",
    "work_code": "S18-W3",
    "stage_id": "stage_s18",
    "stage_code": "S18",
    "task_code": "S18-W3-T6",
    "task_name": "INTERNET ( IF EXIST )",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 174
  },
  {
    "_id": "task_s19_w1_t1_174",
    "work_id": "work_s19_w1",
    "work_code": "S19-W1",
    "stage_id": "stage_s19",
    "stage_code": "S19",
    "task_code": "S19-W1-T1",
    "task_name": "COMPLETE CEILING WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 175
  },
  {
    "_id": "task_s20_w1_t1_175",
    "work_id": "work_s20_w1",
    "work_code": "S20-W1",
    "stage_id": "stage_s20",
    "stage_code": "S20",
    "task_code": "S20-W1-T1",
    "task_name": "WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 176
  },
  {
    "_id": "task_s20_w2_t1_176",
    "work_id": "work_s20_w2",
    "work_code": "S20-W2",
    "stage_id": "stage_s20",
    "stage_code": "S20",
    "task_code": "S20-W2-T1",
    "task_name": "WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 177
  },
  {
    "_id": "task_s20_w3_t1_177",
    "work_id": "work_s20_w3",
    "work_code": "S20-W3",
    "stage_id": "stage_s20",
    "stage_code": "S20",
    "task_code": "S20-W3-T1",
    "task_name": "WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 178
  },
  {
    "_id": "task_s21_w1_t1_178",
    "work_id": "work_s21_w1",
    "work_code": "S21-W1",
    "stage_id": "stage_s21",
    "stage_code": "S21",
    "task_code": "S21-W1-T1",
    "task_name": "WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 179
  },
  {
    "_id": "task_s21_w2_t1_179",
    "work_id": "work_s21_w2",
    "work_code": "S21-W2",
    "stage_id": "stage_s21",
    "stage_code": "S21",
    "task_code": "S21-W2-T1",
    "task_name": "WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 180
  },
  {
    "_id": "task_s21_w3_t1_180",
    "work_id": "work_s21_w3",
    "work_code": "S21-W3",
    "stage_id": "stage_s21",
    "stage_code": "S21",
    "task_code": "S21-W3-T1",
    "task_name": "WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 181
  },
  {
    "_id": "task_s22_w1_t1_181",
    "work_id": "work_s22_w1",
    "work_code": "S22-W1",
    "stage_id": "stage_s22",
    "stage_code": "S22",
    "task_code": "S22-W1-T1",
    "task_name": "WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 182
  },
  {
    "_id": "task_s22_w2_t1_182",
    "work_id": "work_s22_w2",
    "work_code": "S22-W2",
    "stage_id": "stage_s22",
    "stage_code": "S22",
    "task_code": "S22-W2-T1",
    "task_name": "WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 183
  },
  {
    "_id": "task_s22_w3_t1_183",
    "work_id": "work_s22_w3",
    "work_code": "S22-W3",
    "stage_id": "stage_s22",
    "stage_code": "S22",
    "task_code": "S22-W3-T1",
    "task_name": "WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 184
  },
  {
    "_id": "task_s23_w1_t1_184",
    "work_id": "work_s23_w1",
    "work_code": "S23-W1",
    "stage_id": "stage_s23",
    "stage_code": "S23",
    "task_code": "S23-W1-T1",
    "task_name": "WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 185
  },
  {
    "_id": "task_s23_w2_t1_185",
    "work_id": "work_s23_w2",
    "work_code": "S23-W2",
    "stage_id": "stage_s23",
    "stage_code": "S23",
    "task_code": "S23-W2-T1",
    "task_name": "WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 186
  },
  {
    "_id": "task_s23_w3_t1_186",
    "work_id": "work_s23_w3",
    "work_code": "S23-W3",
    "stage_id": "stage_s23",
    "stage_code": "S23",
    "task_code": "S23-W3-T1",
    "task_name": "WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 187
  },
  {
    "_id": "task_s23_w4_t1_187",
    "work_id": "work_s23_w4",
    "work_code": "S23-W4",
    "stage_id": "stage_s23",
    "stage_code": "S23",
    "task_code": "S23-W4-T1",
    "task_name": "WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 188
  },
  {
    "_id": "task_s23_w5_t1_188",
    "work_id": "work_s23_w5",
    "work_code": "S23-W5",
    "stage_id": "stage_s23",
    "stage_code": "S23",
    "task_code": "S23-W5-T1",
    "task_name": "WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 189
  },
  {
    "_id": "task_s23_w6_t1_189",
    "work_id": "work_s23_w6",
    "work_code": "S23-W6",
    "stage_id": "stage_s23",
    "stage_code": "S23",
    "task_code": "S23-W6-T1",
    "task_name": "WORK",
    "work_done_by": "",
    "contractor_type": "",
    "tools": "",
    "materials": "",
    "order": 190
  }
];
